src/objects/AsyncQueue__c.object
<CustomObject>
    <fields>
        <fullName>Job_Type__c</fullName>
        <label>Job Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Queueable</fullName>
                </value>
                <value>
                    <fullName>Batch</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>AsyncQueue</label>
    <nameField>
        <displayFormat>ASQ-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AsyncQueues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WrkfcePlanDelegatorBatchTest.cls
/**
 * @description       : 
 * @author            : Bharath Kumar
 * @group             : 
 * @last modified on  : 09-13-2020
 * @last modified by  : Bharath Kumar
 * Modifications Log 
 * Ver   Date         Author          Modification
 * 1.0   09-13-2020   Bharath Kumar   Initial Version
**/
@isTest
private with sharing class WrkfcePlanDelegatorBatchTest {
    
    @testSetup 
    static void setup() {
        List<Case> cases = new List<Case>();
        List<Case> updatedCases = new List<Case>();
        for(Integer i =0; i < 500; i++) {
            Case caseObj = new Case();
            caseObj.Status='New';
            caseObj.subject='Test ' + i;
            cases.add(caseObj);
        }
        INSERT cases;

        for(Case caseObj : cases) {
            caseObj.Status='Closed';
            updatedCases.add(caseObj);
        }
        UPDATE updatedCases;
    }

    static testmethod void testBatch() { 
        Test.startTest();
        WrkfcePlanDelegatorBatch wrkfcPlanDelegatorBatch = new WrkfcePlanDelegatorBatch();
        Id batchId = Database.executeBatch(wrkfcPlanDelegatorBatch, 15000);
        Test.stopTest();
        Integer queuedJobs = [SELECT count() FROM AsyncQueue__c WHERE Job_Type__c = 'Queueable'];
        System.assertEquals(5, queuedJobs);
    }
}